"""Family-wise error control for multi-cell parameter scans.

Scanning a grid and reporting the best cell's p-value is the most common way to
manufacture a finding. These are the corrections applied to every multi-cell
scan in this project, plus the stability check any survivor must pass.

See ``docs/RESEARCH_METHOD.md`` §5.
"""

from __future__ import annotations

from typing import Optional, Sequence

import numpy as np

__all__ = [
    "one_sample_t",
    "signed_permutation_maxt",
    "holm_bonferroni",
    "half_split_stability",
]


def one_sample_t(x: np.ndarray) -> float:
    """t-statistic for mean(x) != 0. Returns nan for n<2 or zero variance."""
    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = x.size
    if n < 2:
        return float("nan")
    sd = x.std(ddof=1)
    if sd == 0:
        return float("nan")
    return float(x.mean() / (sd / np.sqrt(n)))


def signed_permutation_maxt(
    cells: Sequence[np.ndarray],
    n_permutations: int = 10_000,
    direction: int = 1,
    seed: Optional[int] = None,
) -> dict:
    """Family-wise bar via the permutation distribution of the max **signed** t.

    Why signed, not ``max|t|``: for a directional hypothesis, ``max|t|`` credits
    the null with large excursions in the direction you are *not* claiming. That
    makes the null's maximum bigger than it should be, and the bar correspondingly
    easier to clear. Using ``max|t|`` on a directional claim inflated one of my
    own nulls by roughly **3x** (``RESEARCH_METHOD.md`` §5.1).

    The null is generated by random sign flips of each observation, i.e. the
    one-sample exchangeability assumption that per-trade outcomes are symmetric
    around zero under no edge. Sign flips are applied with a **shared** pattern
    across cells where cells have equal length, preserving the cross-cell
    correlation that makes the family-wise correction meaningful; cells of
    differing length are flipped independently.

    LIMITATION — this null assumes observations are EXCHANGEABLE. It sign-flips
    per observation and scores cells with an unclustered t, so where outcomes are
    clustered (same-day bursts, overlapping positions) the bar it produces is too
    PERMISSIVE. Measured on a real 14-arm trail-configuration scan: one arm scored
    an unclustered t of +3.16 and p_FWER 0.0042 here, but its day-clustered t was
    only +2.27 and a day-BLOCK permutation (flip the sign of a whole day at a
    time, preserving within-day dependence) put it at p_FWER 0.083 — from
    "clears" to "does not clear".

    So: use this for genuinely independent observations. When outcomes are
    clustered, build the null by permuting at the CLUSTER level and score each
    cell with :func:`~.clustering.clustered_tstat`. Pattern:

    >>> udays = pd.unique(days)
    >>> for _ in range(n_perm):                     # doctest: +SKIP
    ...     flip = np.ones(len(days))
    ...     for d in udays:
    ...         if rng.random() < 0.5:
    ...             flip[days == d] = -1.0
    ...     null_max.append(max(clustered_tstat(c * flip, days)["t_clustered"]
    ...                         for c in cells))

    Parameters
    ----------
    cells : one array of per-observation values (e.g. R-multiples) per grid cell.
    direction : +1 tests for a positive mean, -1 for negative.

    Returns
    -------
    dict with ``observed_max_t``, ``best_cell`` (index), ``p_fwer``,
    ``null_quantiles`` (90/95/99th of the null max-t), and ``per_cell_t``.
    """
    if direction not in (1, -1):
        raise ValueError("direction must be +1 or -1")
    arrs = [np.asarray(c, dtype=float) for c in cells]
    arrs = [a[~np.isnan(a)] for a in arrs]
    if not arrs or all(a.size < 2 for a in arrs):
        raise ValueError("need at least one cell with n>=2")

    per_cell_t = np.array([direction * one_sample_t(a) for a in arrs], dtype=float)
    observed = float(np.nanmax(per_cell_t))
    best_cell = int(np.nanargmax(per_cell_t))

    lengths = {a.size for a in arrs}
    shared = len(lengths) == 1
    rng = np.random.default_rng(seed)

    null_max = np.empty(n_permutations, dtype=float)
    for k in range(n_permutations):
        if shared:
            n = arrs[0].size
            flips = rng.choice((-1.0, 1.0), size=n)
            ts = [direction * one_sample_t(a * flips) for a in arrs]
        else:
            ts = [
                direction * one_sample_t(a * rng.choice((-1.0, 1.0), size=a.size))
                for a in arrs
            ]
        null_max[k] = np.nanmax(ts)

    p = float((1 + np.sum(null_max >= observed)) / (1 + n_permutations))
    return {
        "observed_max_t": observed,
        "best_cell": best_cell,
        "p_fwer": p,
        "null_quantiles": {
            "q90": float(np.percentile(null_max, 90)),
            "q95": float(np.percentile(null_max, 95)),
            "q99": float(np.percentile(null_max, 99)),
        },
        "per_cell_t": per_cell_t,
        "n_cells": len(arrs),
        "shared_flips": shared,
    }


def holm_bonferroni(pvalues: Sequence[float], alpha: float = 0.05) -> dict:
    """Holm step-down correction — uniformly more powerful than Bonferroni.

    Use when cells are near-independent or a permutation null is impractical.
    Prefer :func:`signed_permutation_maxt` when cells are correlated, which for
    a parameter grid over the same trade history they almost always are.

    Returns
    -------
    dict with ``reject`` (bool array in the caller's original order),
    ``adjusted`` (step-down adjusted p-values), and ``n_reject``.
    """
    p = np.asarray(pvalues, dtype=float)
    m = p.size
    order = np.argsort(p)
    adj = np.empty(m, dtype=float)

    running = 0.0
    for rank, idx in enumerate(order):
        val = (m - rank) * p[idx]
        running = max(running, val)          # enforce monotonicity
        adj[idx] = min(1.0, running)

    return {
        "reject": adj <= alpha,
        "adjusted": adj,
        "n_reject": int(np.sum(adj <= alpha)),
    }


def half_split_stability(
    values: Sequence[float],
    timestamps: Optional[Sequence] = None,
    min_t: float = 1.0,
) -> dict:
    """Split chronologically in half; require the effect in both halves.

    A survivor of a multi-cell scan has been selected partly on noise. The
    cheapest check that it is not *only* noise is that it appears in both halves
    of its own sample with the same sign. This is a necessary condition, not a
    sufficient one — passing it does not make a finding real, but failing it
    reliably means the effect lives in one regime.

    Returns
    -------
    dict with per-half mean/t/n, ``signs_agree``, and ``stable`` (signs agree
    **and** both halves reach ``min_t`` in the same direction).
    """
    v = np.asarray(values, dtype=float)
    if timestamps is not None:
        order = np.argsort(np.asarray(timestamps))
        v = v[order]
    v = v[~np.isnan(v)]
    if v.size < 4:
        raise ValueError("need at least 4 observations to half-split")

    mid = v.size // 2
    a, b = v[:mid], v[mid:]
    ta, tb = one_sample_t(a), one_sample_t(b)
    signs_agree = bool(np.sign(a.mean()) == np.sign(b.mean()))

    return {
        "first_half": {"mean": float(a.mean()), "t": ta, "n": int(a.size)},
        "second_half": {"mean": float(b.mean()), "t": tb, "n": int(b.size)},
        "signs_agree": signs_agree,
        "stable": bool(
            signs_agree
            and not np.isnan(ta) and not np.isnan(tb)
            and abs(ta) >= min_t and abs(tb) >= min_t
        ),
    }
